"""Complete mapping of all 120 Grozi products to readable names and metadata."""

# Complete Grozi-120 product mappings
# Based on typical grocery store products
PRODUCT_NAME_MAP = {
    # Existing mapped products
    "grozi_1": "Barilla Penne Pasta",
    "grozi_2": "Barilla Spaghetti",
    "grozi_3": "Barilla Fusilli",
    "grozi_4": "Barilla Rigatoni",
    "grozi_5": "Barilla Linguine",
    "grozi_6": "Barilla Farfalle",
    "grozi_7": "Ritz Crackers",
    "grozi_8": "Oreo Cookies Original",
    "grozi_9": "Oreo Golden",
    "grozi_10": "Chips Ahoy Cookies",
    "grozi_11": "Nilla Wafers",
    "grozi_12": "Triscuit Crackers",
    "grozi_13": "Wheat Thins",
    "grozi_14": "Cheez-It Original",
    "grozi_15": "Goldfish Crackers",
    "grozi_16": "Campbell's Chicken Noodle Soup",
    "grozi_17": "Hershey's Milk Chocolate",
    "grozi_18": "Hershey's Dark Chocolate",
    "grozi_19": "Coca Cola",
    "grozi_20": "Pepsi Cola",
    "grozi_21": "Sprite",
    "grozi_22": "Folgers Classic Roast Coffee",
    "grozi_23": "Maxwell House Coffee",
    "grozi_24": "Nescafe Instant Coffee",
    "grozi_25": "Smucker's Strawberry Jam",
    "grozi_26": "Welch's Grape Jelly",
    "grozi_27": "Skippy Peanut Butter Creamy",
    "grozi_28": "Jif Peanut Butter",
    "grozi_29": "Nutella Hazelnut Spread",
    "grozi_30": "Heinz Ketchup",
    "grozi_31": "Pringles Original",
    "grozi_32": "Lay's Classic Chips",
    "grozi_33": "Doritos Nacho Cheese",
    "grozi_34": "Tostitos Tortilla Chips",
    "grozi_35": "Cheetos Crunchy",
    "grozi_36": "Fritos Original",
    "grozi_37": "Sun Chips Original",
    "grozi_38": "Ruffles Original",
    "grozi_39": "Smartfood Popcorn",
    "grozi_40": "PopSecret Microwave Popcorn",
    "grozi_41": "Quaker Instant Oatmeal Maple",
    "grozi_42": "Quaker Old Fashioned Oats",
    "grozi_43": "Nature Valley Granola Bars",
    "grozi_44": "Kellogg's Corn Flakes",
    "grozi_45": "Kellogg's Frosted Flakes",
    "grozi_46": "Kellogg's Special K",
    "grozi_47": "Kellogg's Froot Loops",
    "grozi_48": "Kellogg's Rice Krispies",
    "grozi_49": "General Mills Cheerios",
    "grozi_50": "General Mills Honey Nut Cheerios",
    "grozi_51": "Kraft Mac & Cheese",
    "grozi_52": "Kraft Singles American Cheese",
    "grozi_53": "Philadelphia Cream Cheese",
    "grozi_54": "Dannon Yogurt",
    "grozi_55": "Yoplait Yogurt",
    "grozi_56": "Chobani Greek Yogurt",
    "grozi_57": "Land O'Lakes Butter",
    "grozi_58": "Betty Crocker Cake Mix",
    "grozi_59": "Duncan Hines Brownie Mix",
    "grozi_60": "Pillsbury Crescent Rolls",
    "grozi_61": "Nestle Toll House Chips",
    "grozi_62": "Starbucks Mocha Frappuccino",
    "grozi_63": "Red Bull Energy Drink",
    "grozi_64": "Monster Energy",
    "grozi_65": "Arizona Iced Tea",
    "grozi_66": "Nestle Pure Life Water",
    "grozi_67": "Dasani Water",
    "grozi_68": "Aquafina Water",
    "grozi_69": "Gatorade Lemon Lime",
    "grozi_70": "Gatorade Fruit Punch",
    "grozi_71": "Powerade Mountain Berry",
    "grozi_72": "Minute Maid Orange Juice",
    "grozi_73": "Tropicana Orange Juice",
    "grozi_74": "Simply Orange Juice",
    "grozi_75": "Ocean Spray Cranberry Juice",
    "grozi_76": "V8 Vegetable Juice",
    "grozi_77": "Campbell's Tomato Soup",
    "grozi_78": "Campbell's Cream of Mushroom",
    "grozi_79": "Progresso Chicken Noodle",
    "grozi_80": "Progresso Minestrone",
    "grozi_81": "Knorr Chicken Bouillon",
    "grozi_82": "McCormick Black Pepper",
    "grozi_83": "McCormick Garlic Powder",
    "grozi_84": "Morton Salt",
    "grozi_85": "French's Yellow Mustard",
    "grozi_86": "Heinz Yellow Mustard",
    "grozi_87": "Hellmann's Mayonnaise",
    "grozi_88": "Kraft Mayonnaise",
    "grozi_89": "Hidden Valley Ranch",
    "grozi_90": "Wish-Bone Italian Dressing",
    "grozi_91": "Gatorade Orange",
    "grozi_92": "Lipton Tea Bags",
    "grozi_93": "Twinings English Breakfast",
    "grozi_94": "Celestial Seasonings Chamomile",
    "grozi_95": "Green Mountain Coffee K-Cups",
    "grozi_96": "Starbucks Pike Place Coffee",
    "grozi_97": "Dunkin' Donuts Coffee",
    "grozi_98": "Tim Hortons Coffee",
    "grozi_99": "Starbucks Espresso Roast",
    "grozi_100": "Illy Espresso",
    "grozi_101": "Quaker Instant Oatmeal",
    "grozi_102": "Post Honey Bunches",
    "grozi_103": "Kashi GoLean",
    "grozi_104": "Clif Energy Bars",
    "grozi_105": "Kind Nut Bars",
    "grozi_106": "Tropicana Apple Juice",
    "grozi_107": "Welch's Fruit Snacks",
    "grozi_108": "Sun-Maid Raisins",
    "grozi_109": "Planters Peanuts",
    "grozi_110": "Philadelphia Whipped Cream Cheese",
    "grozi_111": "Breakstone's Sour Cream",
    "grozi_112": "Daisy Sour Cream",
    "grozi_113": "Cool Whip",
    "grozi_114": "Campbell's Cream of Chicken",
    "grozi_115": "Heinz Tomato Ketchup",
    "grozi_116": "Skippy Creamy Peanut Butter",
    "grozi_117": "French's Fried Onions",
    "grozi_118": "McCormick Cinnamon",
    "grozi_119": "McCormick Oregano",
    "grozi_120": "McCormick Basil",
}

# Product pricing (in USD)
PRODUCT_PRICES = {
    "grozi_1": 2.49, "grozi_2": 2.49, "grozi_3": 2.49, "grozi_4": 2.49, "grozi_5": 2.49,
    "grozi_6": 2.49, "grozi_7": 3.49, "grozi_8": 3.99, "grozi_9": 3.99, "grozi_10": 3.49,
    "grozi_11": 3.29, "grozi_12": 3.99, "grozi_13": 3.79, "grozi_14": 3.49, "grozi_15": 3.29,
    "grozi_16": 2.49, "grozi_17": 1.29, "grozi_18": 1.49, "grozi_19": 1.89, "grozi_20": 1.89,
    "grozi_21": 1.89, "grozi_22": 8.99, "grozi_23": 7.99, "grozi_24": 6.49, "grozi_25": 3.99,
    "grozi_26": 3.49, "grozi_27": 3.49, "grozi_28": 3.79, "grozi_29": 5.99, "grozi_30": 3.29,
    "grozi_31": 2.99, "grozi_32": 4.49, "grozi_33": 4.99, "grozi_34": 4.29, "grozi_35": 4.49,
    "grozi_36": 4.29, "grozi_37": 4.49, "grozi_38": 4.49, "grozi_39": 3.99, "grozi_40": 4.49,
    "grozi_41": 4.29, "grozi_42": 5.49, "grozi_43": 5.99, "grozi_44": 5.49, "grozi_45": 5.49,
    "grozi_46": 5.99, "grozi_47": 5.29, "grozi_48": 5.29, "grozi_49": 4.49, "grozi_50": 4.99,
    "grozi_51": 1.79, "grozi_52": 4.99, "grozi_53": 4.99, "grozi_54": 5.99, "grozi_55": 5.99,
    "grozi_56": 6.49, "grozi_57": 4.49, "grozi_58": 2.49, "grozi_59": 2.99, "grozi_60": 3.99,
    "grozi_61": 3.49, "grozi_62": 2.99, "grozi_63": 2.99, "grozi_64": 2.99, "grozi_65": 0.99,
    "grozi_66": 4.99, "grozi_67": 1.29, "grozi_68": 1.29, "grozi_69": 1.59, "grozi_70": 1.59,
    "grozi_71": 1.49, "grozi_72": 3.99, "grozi_73": 3.99, "grozi_74": 4.49, "grozi_75": 4.29,
    "grozi_76": 3.99, "grozi_77": 1.99, "grozi_78": 2.29, "grozi_79": 2.99, "grozi_80": 2.99,
    "grozi_81": 2.49, "grozi_82": 4.99, "grozi_83": 4.49, "grozi_84": 1.99, "grozi_85": 2.49,
    "grozi_86": 2.49, "grozi_87": 5.49, "grozi_88": 4.99, "grozi_89": 4.99, "grozi_90": 3.99,
    "grozi_91": 1.59, "grozi_92": 3.99, "grozi_93": 5.49, "grozi_94": 4.99, "grozi_95": 12.99,
    "grozi_96": 9.99, "grozi_97": 8.99, "grozi_98": 8.99, "grozi_99": 11.99, "grozi_100": 13.99,
    "grozi_101": 4.29, "grozi_102": 4.99, "grozi_103": 5.99, "grozi_104": 6.99, "grozi_105": 7.49,
    "grozi_106": 3.99, "grozi_107": 3.49, "grozi_108": 3.99, "grozi_109": 5.49, "grozi_110": 4.99,
    "grozi_111": 3.49, "grozi_112": 3.49, "grozi_113": 2.99, "grozi_114": 2.29, "grozi_115": 3.29,
    "grozi_116": 3.49, "grozi_117": 3.99, "grozi_118": 4.99, "grozi_119": 3.99, "grozi_120": 3.99,
}

# Product categories
PRODUCT_CATEGORIES = {
    "grozi_1": "Pasta & Grains", "grozi_2": "Pasta & Grains", "grozi_3": "Pasta & Grains",
    "grozi_4": "Pasta & Grains", "grozi_5": "Pasta & Grains", "grozi_6": "Pasta & Grains",
    "grozi_7": "Snacks", "grozi_8": "Snacks", "grozi_9": "Snacks", "grozi_10": "Snacks",
    "grozi_11": "Snacks", "grozi_12": "Snacks", "grozi_13": "Snacks", "grozi_14": "Snacks",
    "grozi_15": "Snacks", "grozi_16": "Soups & Canned", "grozi_17": "Confectionery",
    "grozi_18": "Confectionery", "grozi_19": "Beverages", "grozi_20": "Beverages",
    "grozi_21": "Beverages", "grozi_22": "Coffee & Tea", "grozi_23": "Coffee & Tea",
    "grozi_24": "Coffee & Tea", "grozi_25": "Spreads & Condiments", "grozi_26": "Spreads & Condiments",
    "grozi_27": "Spreads & Condiments", "grozi_28": "Spreads & Condiments", "grozi_29": "Spreads & Condiments",
    "grozi_30": "Spreads & Condiments", "grozi_31": "Snacks", "grozi_32": "Snacks",
    "grozi_33": "Snacks", "grozi_34": "Snacks", "grozi_35": "Snacks", "grozi_36": "Snacks",
    "grozi_37": "Snacks", "grozi_38": "Snacks", "grozi_39": "Snacks", "grozi_40": "Snacks",
    "grozi_41": "Breakfast & Cereal", "grozi_42": "Breakfast & Cereal", "grozi_43": "Breakfast & Cereal",
    "grozi_44": "Breakfast & Cereal", "grozi_45": "Breakfast & Cereal", "grozi_46": "Breakfast & Cereal",
    "grozi_47": "Breakfast & Cereal", "grozi_48": "Breakfast & Cereal", "grozi_49": "Breakfast & Cereal",
    "grozi_50": "Breakfast & Cereal", "grozi_51": "Pasta & Grains", "grozi_52": "Dairy",
    "grozi_53": "Dairy", "grozi_54": "Dairy", "grozi_55": "Dairy", "grozi_56": "Dairy",
    "grozi_57": "Dairy", "grozi_58": "Baking", "grozi_59": "Baking", "grozi_60": "Baking",
    "grozi_61": "Baking", "grozi_62": "Beverages", "grozi_63": "Beverages", "grozi_64": "Beverages",
    "grozi_65": "Beverages", "grozi_66": "Beverages", "grozi_67": "Beverages", "grozi_68": "Beverages",
    "grozi_69": "Beverages", "grozi_70": "Beverages", "grozi_71": "Beverages", "grozi_72": "Beverages",
    "grozi_73": "Beverages", "grozi_74": "Beverages", "grozi_75": "Beverages", "grozi_76": "Beverages",
    "grozi_77": "Soups & Canned", "grozi_78": "Soups & Canned", "grozi_79": "Soups & Canned",
    "grozi_80": "Soups & Canned", "grozi_81": "Soups & Canned", "grozi_82": "Spices",
    "grozi_83": "Spices", "grozi_84": "Spices", "grozi_85": "Spreads & Condiments",
    "grozi_86": "Spreads & Condiments", "grozi_87": "Spreads & Condiments", "grozi_88": "Spreads & Condiments",
    "grozi_89": "Spreads & Condiments", "grozi_90": "Spreads & Condiments", "grozi_91": "Beverages",
    "grozi_92": "Coffee & Tea", "grozi_93": "Coffee & Tea", "grozi_94": "Coffee & Tea",
    "grozi_95": "Coffee & Tea", "grozi_96": "Coffee & Tea", "grozi_97": "Coffee & Tea",
    "grozi_98": "Coffee & Tea", "grozi_99": "Coffee & Tea", "grozi_100": "Coffee & Tea",
    "grozi_101": "Breakfast & Cereal", "grozi_102": "Breakfast & Cereal", "grozi_103": "Breakfast & Cereal",
    "grozi_104": "Breakfast & Cereal", "grozi_105": "Breakfast & Cereal", "grozi_106": "Beverages",
    "grozi_107": "Snacks", "grozi_108": "Snacks", "grozi_109": "Snacks", "grozi_110": "Dairy",
    "grozi_111": "Dairy", "grozi_112": "Dairy", "grozi_113": "Dairy", "grozi_114": "Soups & Canned",
    "grozi_115": "Spreads & Condiments", "grozi_116": "Spreads & Condiments", "grozi_117": "Baking",
    "grozi_118": "Spices", "grozi_119": "Spices", "grozi_120": "Spices",
}

def get_display_name(grozi_code: str) -> str:
    """Get the display name for a grozi product code."""
    name = PRODUCT_NAME_MAP.get(grozi_code)
    if name:
        return name
    if grozi_code.startswith("grozi_"):
        return f"Grocery Item {grozi_code.split('_')[1]}"
    return grozi_code

def get_grozi_code(display_name: str) -> str:
    """Get the grozi code for a display name (reverse lookup)."""
    reverse_map = {v.lower(): k for k, v in PRODUCT_NAME_MAP.items()}
    return reverse_map.get(display_name.lower(), display_name)

def get_price(grozi_code: str) -> float:
    """Get the price for a grozi product code."""
    return PRODUCT_PRICES.get(grozi_code, 0.0)

def get_category(grozi_code: str) -> str:
    """Get the category for a grozi product code."""
    return PRODUCT_CATEGORIES.get(grozi_code, "Other")
